name: Gunslinger
version: 1.3.7-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.gunslinger.Main
description: A player is chosen at each match to be a gunslinger. His objective is to kill everyone else in the match. The other players will be trying to be the last one alive by killing other players in the match. Although, obviously, they also need to be constantly watching out for the gunslinger.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  gunslinger:
    aliases: [gs]
permissions:
  gs.select:
    default: op
  gs.kits.use.*:
    default: op
  gs.kits.modify:
    default: op
  gs.kits.*:
    default: op
    children:
      gs.kits.modify: true
      gs.kits.use.*: true
  gs.*:
    default: op
    children:
      gs.kits.*: true
      gs.select: true